---

- name: set timezone to Moscow
  timezone:
    name: Europe/Moscow

- name: set up forward packages across routers
  sysctl:
    name: net.ipv4.conf.all.forwarding
    value: '1'
    state: present
    reload: true

- name: base set up OSPF
  template: 
    src: daemons.j2
    dest: /etc/frr/daemons
    owner: frr
    group: frr
    mode: 0640

# Отключаем запрет ассиметричного роутинга 
- name: set up asynchronous routing
  sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: '0'
    state: present

# Копируем файл frr.conf на хосты, указываем владельца и права
- name: set up OSPF 
  template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
    mode: 0640
